name: vprofile action
on: workflow_dispatch
env:
  AWS_REGION: us-east-2
  ECR_REPOSITORY: vprofileapp
  EKS_CLUSTER: vprofile-eks

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Maven test
        run: mvn test

      - name: Checkstyle
        run: mvn checkstyle:checkstyle

      - name: Setup java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      #setup sonar scanner cli

      - name: Setup sonarqube
        uses: warchant/setup-sonar-scanner@v7

    #run sonar scan
      - name: Sonarqube scan
        run: sonar-scanner
          -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
          -Dsonar.sources=src/ 
          -Dsonar.host.url=${{ secrets.SONAR_URL }} 
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
          -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
          -Dsonar.junit.reportsPath=target/surefire-reports/
          -Dsonar.jacoco.reportPaths=target/jacoco.exec
          -Dsonar.checkstyle.reportPaths=target/checkstyle-result.xml
          -Dsonar.java.binaries=target/test-classes/com/visualpathit/account

      #check quality gate

      - name: Sonarqube quality gate
        id: qualitygate
        uses: sonarsource/sonar-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_URL }}

      # - name: Sonarqube quality gate status
      #   if: ${{ steps.qualitygate.outputs.quality_gate_status != 'OK' }}
      #   run: |
      #     echo "Sonarqube quality gate status: ${{ steps.qualitygate.outputs.quality_gate_status }}"
      #     echo "Sonarqube quality gate conditions: ${{ steps.qualitygate.outputs.quality_gate_conditions }}"
      #     exit 1  
          